services:
  svelte-kit:
    container_name: dev-mc-scrpt-live
    image: mc-scrpt-live:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - yarn-cache:/usr/local/share/.cache/yarn
      - ./:/website/

volumes:
  yarn-cache:
