services:
  svelte-kit:
    container_name: dev-mc-scrpt-live
    working_dir: /website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # Vite
      - 4173:4173 # Playwright
    volumes:
      - ./:/website/
    tty: true
