services:
  mc-scrpt-dev:
    container_name: mc-scrpt-dev
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "6006:6006"
      - "9009:9009"
    volumes:
      - ./:/app/
    stdin_open: true
    tty: true
