FROM php:7.4-fpm-alpine

RUN apk add --update --no-cache libgd libpng-dev libjpeg-turbo-dev freetype-dev

RUN docker-php-ext-install -j$(nproc) gd

# #####################################################
# #####################################################

## Use offical ubuntu:20.04 image
#FROM httpd:20.04
#
## Set timezone
#ENV TZ=Europe/Berlin
#
## Set geographic area using above variable
## This is necessary, otherwise building the image doesn't work
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#
## Remove annoying messages during package installation
#ARG DEBIAN_FRONTEND=noninteractive
#
## Install packages: web server & PHP plus extensions
#RUN apt-get update && apt-get install -y \
#  apache2 \
#  apache2-utils \
#  ca-certificates \
#  php \
#  libapache2-mod-php \
#  php-curl \
#  php-dom \
#  php-gd \
#  php-intl \
#  php-json \
#  php-mbstring \
#  php-xml \
#  php-zip && \
#  apt-get clean && rm -rf /var/lib/apt/lists/*
#
## Copy virtual host configuration from current path onto existing apache-config.conf
#COPY default.conf /etc/apache2/sites-available/apache-config.conf
#
## Remove default content (existing index.html)
#RUN rm /var/www/html/*
#
## Activate Apache modules headers & rewrite
#RUN a2enmod headers rewrite
#
## Change web server's user id to match local user, replace with your local user id
#RUN usermod --uid 1001 www-data
#
## Tell container to listen to port 80 at runtime
#EXPOSE 80
#
## Start Apache web server
#CMD [ "/usr/sbin/apache2ctl", "-DFOREGROUND" ]

# #####################################################
# #####################################################

#FROM php:7.4-apache
#
#WORKDIR "/var/www/html"
#
##RUN apt-get update -y && apt-get install -y sendmail libpng-dev
#RUN apt-get update && apt-get install -y
#
##RUN apt install -y libxml2-dev
#RUN apt install -y curl
#
#
#RUN docker-php-ext-install xml
#RUN docker-php-ext-install dom
#RUN docker-php-ext-install gd
#RUN docker-php-ext-install intl
#RUN docker-php-ext-install json
#RUN docker-php-ext-install mbstring
#RUN docker-php-ext-install zip
#
#RUN apt-get clean
#
#COPY . /var/www/html/
#
#EXPOSE 80