name: Sync Event Data

on:
  workflow_dispatch:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 5 * * 7"
#  workflow_dispatch:
#    branches:
#      - main

jobs:
  sync-event:
    name: Update Website Events
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          
      - name: Install dependencies 📦
        run: |
          npm install

      - name: Sync services
        run: |
          npx tsx scripts/sync-events.ts
        env:
          GAS_URL: ${{ secrets.GAS_URL }}
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated event data
          committer_name: GitHub Actions
          committer_email: actions@github.com
      
      - name: Build
        run: |
          npm run build
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build
      
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v4
