name: Sync event log

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.0.2
      - name: Install dependencies 📦
        run: |
          yarn install
      - name: Sync event log
        run: |
          echo $GAS_URL
          yarn sync
