name: Sync Event Data

on: workflow_dispatch
#  schedule:
#    - cron: "0 5 * * 7"
#  workflow_dispatch:
#    branches:
#      - main

jobs:
  sync-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "20.15.0"
      - name: Install dependencies 📦
        run: |
          npm install
      - name: Sync services
        run: |
          npx tsx scripts/sync-events.ts
        env:
          GAS_URL: ${{ secrets.GAS_URL }}
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated event data
          committer_name: GitHub Actions
          committer_email: actions@github.com
