name: Sync Event Data

on:
  schedule:
    - cron: "0 5 * * 4" # Every Thursday at 5:00 AM UTC
  workflow_dispatch:

jobs:
  sync-event:
    name: Update Website Events
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies 📦
        run: |
          npm install

      - name: Sync services
        run: |
          npx tsx scripts/sync-events.ts
        env:
          VITE_GAS_URL: ${{ secrets.VITE_GAS_URL }}
          VITE_DEPLOYMENT_ID: ${{ secrets.VITE_DEPLOYMENT_ID }}

      - name: Debug files
        run: ls -l --time-style=long-iso src/data

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Chore: Update Event Data"
          add: "src/data/*.json"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
