name: Update Website

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    name: Deploy Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.0"
      - name: Install dependencies 📦
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'  # Deploy only on the main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # The default output directory for adapter-static
